AllCops:
  TargetRubyVersion: 3.0

inherit_gem:
  syntax_tree: config/rubocop.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Style/IfUnlessModifier:
  Enabled: false
