AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - ./spec/expand/output/*
    - ./vendor/**/*

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-on-rbs
  - rubocop-rubycw

inherit_gem:
  syntax_tree: config/rubocop.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Style/IfUnlessModifier:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
