name: verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies (Ruby)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Run tests
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          pip3 install online-judge-verify-helper
          bundle install
          oj-verify run ./verify/*
